-- migrate:up
-- Reference lists. Admins may add rows (e.g. a new theme) without a migration.

CREATE TABLE catalog.ref_lod_level (
  lod         smallint PRIMARY KEY CHECK (lod BETWEEN 0 AND 4),
  name        text NOT NULL,
  description text
);
COMMENT ON TABLE  catalog.ref_lod_level IS 'Level of Detail per CityGML 2.0 (0 = footprint/terrain ... 4 = interior).';

CREATE TABLE catalog.ref_theme (
  code        text PRIMARY KEY CHECK (code ~ '^[a-z0-9_]+$'),
  name        text NOT NULL,
  description text,
  citydb_objectclass_hint text[],
  sort        int NOT NULL DEFAULT 100
);
COMMENT ON TABLE  catalog.ref_theme IS 'Subject of a layer: building, bridge, road, terrain ... Add a row to support a new theme.';
COMMENT ON COLUMN catalog.ref_theme.code IS 'Short lowercase code, used in the lineage tag (dataset.theme.lodN). Do not change after use.';
COMMENT ON COLUMN catalog.ref_theme.citydb_objectclass_hint IS 'Typical 3DCityDB class names for this theme (documentation only).';

CREATE TABLE catalog.ref_generated_by (
  code        text PRIMARY KEY CHECK (code ~ '^[a-z0-9_]+$'),
  name        text NOT NULL,
  description text
);
COMMENT ON TABLE catalog.ref_generated_by IS 'Who produced the data: an external provider, NARAGA, or manual work.';

CREATE TABLE catalog.ref_layer_status (
  code text PRIMARY KEY, name text NOT NULL, description text, sort int NOT NULL
);
COMMENT ON TABLE catalog.ref_layer_status IS 'Lifecycle of a layer. Allowed moves are enforced by the database.';

CREATE TABLE catalog.ref_tileset_status (
  code text PRIMARY KEY, name text NOT NULL, description text, sort int NOT NULL
);
COMMENT ON TABLE catalog.ref_tileset_status IS 'Lifecycle of one 3D Tiles build.';

INSERT INTO catalog.ref_lod_level (lod, name, description) VALUES
  (0, 'LOD0', 'Footprint / terrain (2.5D)'),
  (1, 'LOD1', 'Block model (extruded footprint)'),
  (2, 'LOD2', 'Roof shapes and thematic surfaces'),
  (3, 'LOD3', 'Detailed architecture (openings)'),
  (4, 'LOD4', 'Interior (rooms)')
ON CONFLICT DO NOTHING;

INSERT INTO catalog.ref_theme (code, name, description, citydb_objectclass_hint, sort) VALUES
  ('building',   'Building',   'Buildings and building parts', ARRAY['Building','BuildingPart','BuildingRoom'], 10),
  ('bridge',     'Bridge',     'Bridges',                      ARRAY['Bridge'], 20),
  ('road',       'Road',       'Roads and transport',          ARRAY['Road','TrafficArea'], 30),
  ('terrain',    'Terrain',    'Relief / DTM',                 ARRAY['TINRelief'], 40),
  ('vegetation', 'Vegetation', 'Trees and vegetation',         ARRAY['SolitaryVegetationObject','PlantCover'], 50),
  ('water',      'Water',      'Water bodies',                 ARRAY['WaterBody'], 60),
  ('furniture',  'City furniture', 'Street furniture',         ARRAY['CityFurniture'], 70),
  ('generic',    'Generic',    'Other city objects',           ARRAY['GenericCityObject'], 90)
ON CONFLICT DO NOTHING;

INSERT INTO catalog.ref_generated_by (code, name, description) VALUES
  ('external', 'External provider', 'Delivered by a third party'),
  ('naraga',   'NARAGA',            'Generated by the NARAGA pipeline'),
  ('manual',   'Manual',            'Produced or edited by hand')
ON CONFLICT DO NOTHING;

INSERT INTO catalog.ref_layer_status (code, name, description, sort) VALUES
  ('draft',     'Draft',     'Being prepared, not visible to the frontend', 10),
  ('validated', 'Validated', 'Import checked and passed',                  20),
  ('published', 'Published', 'Visible to the frontend (has an active tileset)', 30),
  ('archived',  'Archived',  'Retired, kept for history',                  40)
ON CONFLICT DO NOTHING;

INSERT INTO catalog.ref_tileset_status (code, name, description, sort) VALUES
  ('building', 'Building', 'Conversion/upload in progress', 10),
  ('ready',    'Ready',    'Complete, can be served',        20),
  ('failed',   'Failed',   'Conversion or upload failed',    30),
  ('retired',  'Retired',  'Replaced or withdrawn',          40)
ON CONFLICT DO NOTHING;

-- migrate:down
DROP TABLE IF EXISTS catalog.ref_tileset_status, catalog.ref_layer_status, catalog.ref_generated_by, catalog.ref_theme, catalog.ref_lod_level CASCADE;
