-- Project seed: OIKN. Idempotent (safe to run repeatedly). Values marked TODO are open items to confirm.
SELECT set_config('app.user', 'seed', false);

INSERT INTO catalog.dataset (code, name, description, region, source_system, owner_org, generated_by, crs_epsg, vertical_datum, attribution)
VALUES
  ('oikn', 'OIKN', '3D city model of Ibu Kota Nusantara delivered by the external provider', 'Ibu Kota Nusantara (IKN)',
   'external', NULL, 'external', NULL /* TODO source EPSG */, 'unknown' /* TODO vertical datum */, NULL),
  ('ikn_naraga', 'IKN generated by NARAGA', '3D city model of IKN generated by the NARAGA pipeline', 'Ibu Kota Nusantara (IKN)',
   'naraga', NULL, 'naraga', NULL, 'unknown', NULL)
ON CONFLICT (code) DO NOTHING;

-- Planned layers (all start as draft). LOD2 NARAGA is only prepared, filled 14-16 Oct.
INSERT INTO catalog.layer (dataset_id, theme_code, lod, title)
SELECT d.id, 'building', v.lod, v.title
FROM (VALUES ('oikn', 1::smallint, 'OIKN buildings LOD1'),
             ('oikn', 4::smallint, 'OIKN buildings LOD4 (test sample)'),
             ('ikn_naraga', 2::smallint, 'IKN NARAGA buildings LOD2')) AS v(code, lod, title)
JOIN catalog.dataset d ON d.code = v.code
ON CONFLICT (dataset_id, theme_code, lod) DO NOTHING;
